# Compositional space

If there is something different when you learn thermodynamics in the high school and when it is recalled in a more advanced course in petrology is the importance of the kind of matter (after all we are dealing with diferent kind of rocks with diferent compositions). In petrology we are chiefely concern about changes in matter (aka mineral transformation) so it is important to deal with compositions. If we disregard the crust, the composition of the bulk silicate Earth is rather simple (in its extreme laconic representation it can be defined as MgO-SiO2 (then FeO-Al2O3-CaO-H2O). Let's explore some possible reactions in this system

In [2]:
import numpy as np

Let's imagine we want to balance a quemical mineral reaction, for instances between forsterite Mg2SiO4 (fo), quartz SiO2 (q) and periclase MgO (per). First write the vectors defining these minerals in the MgO and SiO2 compositional space (2 compositions, k = 2). 

|  component (k)   | fo | q | per |
|------|---|---|---|
|MgO   | 2 | 0 | 1 |
|SiO2  | 1 | 1 | 0 |


In [3]:
fo = np.array([[2], [1]])
q  = np.array([[0], [1]])
per = np.array([[1], [0]])

you can solve this problem by writing up a system of equations (2 equations, one per component). So let's call $x$ and $y$ the amount of forsterite and quartz (in number of moles) respectively. So for the first component MgO we have,

$$
2x + 0y = 1 
$$

and for the SiO2

$$
1x + 1y = 0 
$$

so in the school you would write

\begin{cases} 2x = 1 \\ x + y = 0 \end{cases}

a quite easy to solve equation... $x = 1/2$ and $y = -1/2$.

In the high school, they probably told you to write the same in matrix notation,

$$
\begin{bmatrix} 2 & 0 \\ 1 & 1 \end{bmatrix}
\begin{bmatrix} x \\ y \end{bmatrix} =
\begin{bmatrix} 1 \\ 0 \end{bmatrix}
$$

$$\textbf{A}\cdot \textbf{x} = \textbf{b}$$

where $\textbf{b}$ is the vector defining periclase. 

In [4]:
b = np.array([1, 0])

So now let's do this calculation with python (numpy). First create the matrix $\textbf{A}$ by appending the forsterite and quartz vector. 

In [5]:
A = np.append(fo,q,axis = 1)
print(A)

[[2 0]
 [1 1]]


The funny 
``` python 
x = 1 
```
means the way the vectors are appended (try without it to see what happens). And now simply solve for $\textbf{x}$

In [6]:
x = np.linalg.inv(A).dot(b)
print(x)

[ 0.5 -0.5]


So now we are in the position to write the chemical balanced equation as 

1/2 for - 1/2 q = per

or more naturally

1/2 fo = per + 1/2 q 

or

fo = 2per + q 

If you feel you might a refresh in linear algebra try this winkling little mathematician from the MIT
https://www.youtube.com/watch?v=J7DzL2_Na80

# Another way to do it
You might wonder how do you know that periclase is the product phase of reacting quartz and forsterite. The answer is indeed irrelevant, you might interchange periclase by forsterite and you will get the same answer. Actually the reallity is that periclase and quartz are the product phases of the decomposition of forsterite (or the reverse, periclase and quartz react to form forsterite). So all the three vectors are related, no matter which mineral phase you use as $\textbf{b}$ vector. A more elegant way to solve the problem is to consider as $z$ as the amount of periclase and add a new column to our matrix, by noting that

\begin{cases} 2x + z = 0 \\ x + y + z = 0 \end{cases}

or
$$
\begin{bmatrix} 2 & 0 & 1\\ 1 & 1 & 1 \end{bmatrix}
\begin{bmatrix} x \\ y \\ z \end{bmatrix} =
\begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}
$$

So we can simply look for the so-called null space of the matrix composed of all phases $\textbf{C}$. 

$$
C = \begin{bmatrix} 2 & 0 & 1\\ 1 & 1 & 1 \end{bmatrix}
$$


In [7]:
C = np.array([[2,0,1],[1,1,0]])
print(C)

[[2 0 1]
 [1 1 0]]


In [8]:
from scipy.linalg import null_space
ns = null_space(C)

In [9]:
print(ns)

[[-0.40824829]
 [ 0.40824829]
 [ 0.81649658]]


To make it prettier divide by the smaller coefficient

In [10]:
ns/ns[0,0]

array([[ 1.],
       [-1.],
       [-2.]])

that gives you the same result, 
```python
1.0 fo  -1.0 q - 2.0 per = 0 
1.0 fo = 1.0 q 2.0 per 
```

for completeness the $\textbf{C}$ matrix has a rank of 2, meaning that all minerals (vectors) can be defined in a cartesian coordinates (2-dimensions). This is another way to say that the systems has efectively 2 components.

In [11]:
from numpy.linalg import matrix_rank
matrix_rank(C)

2

# Exercise
Write the linear dependency (i.e. reactions) between spinel MgAl2O4 (sp), enstatite Mg2Si2O6 (en), forsterite Mg2SiO4 (fo) and cordierite Mg2Al4Si5O18 (crd)

|k     |sp |en |fo |crd|
|------|---|---|---|---|
|MgO   | 1 | 2 | 2 | 2 |
|SiO2  | 0 | 2 | 1 | 5 |
|Al2O3 | 1 | 0 | 0 | 2 |

In [12]:
D = np.array([[1,2,2,2],[0,2,1,5],[1,0,0,2]])
print(C)

[[2 0 1]
 [1 1 0]]


In [13]:
Ex = null_space(D)
print(Ex)

[[-0.26967994]
 [-0.67419986]
 [ 0.67419986]
 [ 0.13483997]]


In [14]:
Ex/Ex[1,0]

array([[ 0.4],
       [ 1. ],
       [-1. ],
       [-0.2]])

```python
0.400 sp 1.00 en = 1.00 fo 0.200 crd  
```

This system has 3 components (independently variable components)

In [15]:
from numpy.linalg import matrix_rank
matrix_rank(D)

3

# What about having more mineral phases in the system?

Sillimanite can also defined in the previous 3 component system (k = 3). 


|k     |sp |en |fo |crd|sill|
|------|---|---|---|---|---|
|MgO   | 1 | 2 | 2 | 2 | 0 |
|SiO2  | 0 | 2 | 1 | 5 | 1 |
|Al2O3 | 1 | 0 | 0 | 2 | 1 |

In [19]:
E = np.array([[1,2,2,2,0],[0,2,1,5,1],[1,0,0,2,1]])
phases_E = np.array(['sp', 'en', 'fo', 'crd', 'sill'])
np.linalg.matrix_rank(D)

3

In [20]:
T = null_space(E)
print(T)

[[-0.14515292 -0.33909446]
 [-0.71206351 -0.05629959]
 [ 0.53747291  0.45201787]
 [ 0.24716706 -0.22617105]
 [-0.3491812   0.79143655]]


The null space of $\textbf{C}$ contains now two columns (two independent reactions). These 2 independent reactions span the reaction space and they can be combined linearly to generate all the reactions in that space. Because in a 3 components systems only 4 (non-degenerated) phases can be involved in an univariant reaction, the number of univariant reactions taking 5 phases is 5. You can find these 5 equations by zerothing one coefficient of on column of the null by using the other column. For instance in the previous reaction we computed sill is lacking, customary this is represented as [sill]. So we can make the last row of the first column zeroth by dividing the last column by 

In [21]:
no_sill = T[:,0]-T[4][0]*T[:,1]/T[4][1]
print(phases_E)
no_sill/no_sill[1]

['sp' 'en' 'fo' 'crd' 'sill']


array([ 0.4,  1. , -1. , -0.2, -0. ])

giving the same result as above

```python
0.400 sp 1.00 en = 1.00 fo 0.200 crd 0 sill
```

# Back to real world. Taking into account uncertainties

In [22]:
F = np.array([[1,0,3,2,3],[2,3,0,7,6],[1,1,2,3,4],[0,2,1,2,5],[4,1,0,9,2]])
error = np.array([[-0.0253,0.0055,0.0117,0.0039,0.0478],
                  [-0.0152,0.0242,-0.0202,0.0269,0.0259],
                  [-0.0066,0.0106,0.0023,0.0039,0.0258],
                  [0.0005,0.0008,-0.0268,-0.0192,0.0057],
                  [-0.0041,0.0287,-0.0332,0.0255,0.0132]]) 

In [23]:
np.linalg.matrix_rank(F)

3

In [24]:
np.linalg.matrix_rank(F+error)

5

A popular technique to treat near-deficient rank matrices is the singular value decomposition (SVD) technique

In [25]:
U, s, Vt = np.linalg.svd(F+error)

In [26]:
s

array([1.56308218e+01, 5.96438169e+00, 3.14968041e+00, 2.16637426e-02,
       7.78378473e-03])

In [27]:
V = Vt.transpose()

In [28]:
V

array([[-0.26608873,  0.32965724, -0.26150617, -0.85032531,  0.17054116],
       [-0.22060015, -0.16677419,  0.48662966,  0.02086705,  0.82841903],
       [-0.10569486, -0.36172741, -0.81836692,  0.21957155,  0.37422693],
       [-0.75477376,  0.49146556, -0.04546687,  0.42345446, -0.08600738],
       [-0.54742811, -0.7008048 ,  0.15170512, -0.22132802, -0.37039784]])

In [32]:
V[:,3:5]

array([[-0.85032531,  0.17054116],
       [ 0.02086705,  0.82841903],
       [ 0.21957155,  0.37422693],
       [ 0.42345446, -0.08600738],
       [-0.22132802, -0.37039784]])

that can be compared to the original (free of errors) Matrix. Note the change of position and sign of columns.

In [36]:
null_space(F)

array([[-0.13491512,  0.85545187],
       [-0.82901362,  0.01537612],
       [-0.38077803, -0.20617491],
       [ 0.06745756, -0.42772594],
       [ 0.38077803,  0.20617491]])

In [37]:
U_0, s_0, Vt_0 = np.linalg.svd(F)

In [38]:
V_0 = Vt_0.transpose()
V_0[:,3:5]

array([[-0.13491512,  0.85545187],
       [-0.82901362,  0.01537612],
       [-0.38077803, -0.20617491],
       [ 0.06745756, -0.42772594],
       [ 0.38077803,  0.20617491]])

In [39]:
s_0

array([1.55856448e+01, 5.93428322e+00, 3.14196714e+00, 5.10185451e-16,
       1.53299893e-16])